Repository Skatteetaten/terraform-nomad-minio, pull requests merged in 2020-11, with the labels that each got.

#74 Issue 72 & 73 configurability fixes
  CHANGELOG.md
  README.md
  conf/nomad/minio.hcl
  main.tf
  variables.tf
Labels: type/enhancement

#69 refactor and proper rendering of credentials
  CHANGELOG.md
  Makefile
  README.md
  conf/nomad/mc.hcl
  conf/nomad/minio.hcl
  dev/.env
  dev/ansible/02_run_terraform.yml
  dev/ansible/03_run_tests.yml
  dev/ansible/04_upload_files.yml
  dev/ansible/05_test_persistence.yml
  dev/vagrant/bootstrap/vault/post/01-create_vault_policy_to_read_secrets.yml
  dev/vagrant/conf/nomad/00-enable_vault.hcl
  example/README.md
  example/minio_standalone/README.md
  example/minio_standalone/main.tf
  example/minio_standalone/providers.tf
  example/minio_standalone/variables.tf
  example/providers.tf
  example/vagrant_box_example/README.md
  example/vagrant_box_example/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#80 added user defined resource variables and output port number
  CHANGELOG.md
  README.md
  conf/nomad/minio.hcl
  main.tf
  outputs.tf
  variables.tf
Labels: type/enhancement

#79 updated to fit hashistack 0.7.1
  CHANGELOG.md
  Vagrantfile.default
  dev/ansible/05_test_persistence.yml
  dev/vagrant/bootstrap/nomad/post/030-update-nomad-write-default-policy.yml
  example/minio_standalone/providers.tf
Labels: type/enhancement

#81 Release 0.3.0
  CHANGELOG.md
Labels: minor

#84 Hotfix: Removed "bug" in Vault policy & upated readme
  CHANGELOG.md
  README.md
  dev/vagrant/bootstrap/vault/post/01-create_vault_policy_to_read_secrets.yml
Labels: type/bug, type/documentation

#88 updated docs
  README.md
  main.tf
Labels: skip-changelog, type/documentation

#89 added skip-duplicate-runs action
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  README.md
Labels: theme/ci, type/enhancement

#91 Issue 85 increase sidecar memory
  CHANGELOG.md
  conf/nomad/minio.hcl
  example/minio_standalone/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#93 [minio] Updated variables
  CHANGELOG.md
  Makefile
  README.md
  conf/nomad/mc.hcl
  conf/nomad/minio.hcl
  dev/vagrant/bootstrap/vault/post/01-create_vault_policy_to_read_secrets.yml
  example/minio_standalone/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#94 Release 0.4.0
  CHANGELOG.md
Labels: minor

#95 Revert "Release 0.4.0"
  CHANGELOG.md
Labels: revert-release
