Repository Skatteetaten/terraform-nomad-minio, pull requests merged in 2020-10, with the labels that each got.

#33 Updated terraform-provider-nomad and vault provider version
  CHANGELOG.md
  example/vagrant_box_example/main.tf
  template_example/example/standalone/main.tf
Labels: enhancement

#31 added host volume
  .github/workflows/on_pr_push_master.yml
  .gitignore
  CHANGELOG.md
  README.md
  conf/nomad/minio.hcl
  dev/vagrant/conf/nomad/99-mount-host-volume.hcl
  dev/vagrant/conf/post_bootstrap/01-update-nomad-write-default-policy.yml
  dev/vagrant/conf/post_bootstrap/host_volume_policy.hcl
  dev/vagrant/conf/pre_bootstrap/00-create_dir_for_persisting_data.yml
  example/main.tf
  main.tf
  variables.tf
Labels: enhancement

#38 Added tests to verify host volume for minio
  .github/action/create-env.py
  CHANGELOG.md
  Makefile
  dev/ansible/03_run_tests.yml
  dev/ansible/04_upload_files.yml
  dev/ansible/05_test_persistence.yml
  example/resources/data/csv/test-persistence-file.csv
Labels: enhancement, test

#40 Automate release process
  .github/action/find-replace.py
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
Labels: ci, enhancement

#43 Switch for host volume
  CHANGELOG.md
  README.md
  conf/nomad/minio.hcl
  example/README.md
  example/main.tf
  main.tf
  variables.tf
Labels: bug

#45 Removed dependency of vault gen/passwd plugin
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  dev/ansible/01_generate_secrets_vault.yml
  dev/vagrant/conf/post_bootstrap/00-install-plugin-vault-secrets-gen.yml
Labels: enhancement

#46 Release 0.1.0
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
Labels: minor

#49 Updated makefile
  CHANGELOG.md
  Makefile
Labels: ci, enhancement

#51 Updated github workflow file
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
Labels: ci

#55 Added github templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/general_issue.md
  .github/pull_request_template.md
  CHANGELOG.md
Labels: theme/ci

#56 Sync
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  Makefile
  README.md
  Vagrantfile.default
  dev/ansible/00_create_intention.yml
  dev/ansible/01_generate_secrets_vault.yml
  dev/ansible/03_run_tests.yml
  dev/ansible/04_upload_files.yml
  dev/ansible/05_test_persistence.yml
  dev/vagrant/bootstrap/README.md
  dev/vagrant/bootstrap/nomad/post/030-update-nomad-write-default-policy.yml
  dev/vagrant/bootstrap/nomad/post/host_volume_policy.hcl
  dev/vagrant/bootstrap/nomad/pre/00-create_dir_for_persisting_data.yml
  dev/vagrant/conf/README.md
  dev/vagrant/conf/post_bootstrap/README.md
  example/providers.tf
  template_example/.env
  template_example/Vagrantfile
  template_example/conf/nomad/countdash.hcl
  template_example/dev/ansible/01_build_docker_image.yml
  template_example/dev/ansible/02_run_terraform.yml
  template_example/dev/ansible/playbook.yml
  template_example/dev/vagrant/conf/consul/99-override.hcl
  template_example/dev/vagrant/conf/nomad/99-override.hcl
  template_example/dev/vagrant/conf/post_ansible.sh
  template_example/dev/vagrant/conf/post_bootstrap/00-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/01-poststart-example.yml
  template_example/dev/vagrant/conf/post_bootstrap/02-poststart-example.yml
  template_example/dev/vagrant/conf/pre_ansible.sh
  template_example/dev/vagrant/conf/pre_bootstrap/00-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/01-prestart-example.yml
  template_example/dev/vagrant/conf/pre_bootstrap/02-prestart-example.yml
  template_example/dev/vagrant/conf/vault/99-override.hcl
  template_example/docker/.dockerignore
  template_example/docker/Dockerfile
  template_example/docker/conf/certificates/.gitignore
  template_example/docker/conf/certificates/README.md
  template_example/example/standalone/main.tf
  template_example/example/standalone/nomad_acl.tf
  template_example/example/standalone/variables.tf
  template_example/main.tf
  template_example/outputs.tf
  template_example/variables.tf
Labels: type/enhancement

#59 Changed path for data_dir local/data -> minio/data
  CHANGELOG.md
  example/main.tf
  variables.tf
Labels: type/enhancement

#60 Release 0.2.0
  CHANGELOG.md
Labels: minor

#67 Added canary deployment and switch
  CHANGELOG.md
  README.md
  conf/nomad/minio.hcl
  example/main.tf
  main.tf
  variables.tf
Labels: type/enhancement

#68 Updated README and added intentions section
  CHANGELOG.md
  README.md
Labels: type/documentation
