Repository Skatteetaten/terraform-nomad-minio, pull requests merged in 2020-09, with the labels that each got.

#13 Feature/add examples
  .gitignore
  CHANGELOG.md
  README.md
  dev/ansible/03_run_tests.yml
  dev/ansible/04_upload_files.yml
  example/README.md
  example/resources/data/avro-tweet/tweet1.snappy.avro
  example/resources/data/avro-tweet/tweet2.snappy.avro
  example/resources/data/csv/iris.csv
  example/resources/data/json/ex1.json
  example/resources/data/json/ex2.json
  example/resources/data/proto-message/info1.data
  example/resources/data/proto-message/info2.data
  example/resources/schemes/.gitignore
  example/resources/schemes/Makefile
  example/resources/schemes/avro/tweet1.json
  example/resources/schemes/avro/tweet2.json
  example/resources/schemes/avro/twitter_scheme.avsc
  example/resources/schemes/proto/info.proto
  example/resources/schemes/proto/info1.text
  example/resources/schemes/proto/info2.text
  outputs.tf
  variables.tf
Labels: documentation, enhancement

#14 Prepare for release/0.0.3
  CHANGELOG.md
  README.md
Labels: documentation

#19 Vault gen password
  .github/workflows/on_pr_push_master.yml
  CHANGELOG.md
  dev/ansible/01_generate_secrets_vault.yml
  dev/ansible/02_run_terraform.yml
  dev/ansible/03_run_tests.yml
  dev/ansible/04_upload_files.yml
  dev/vagrant/conf/post_bootstrap/00-poststart-example.yml
  dev/vagrant/conf/vault/99-override.hcl
  example/main.tf
  example/variables.tf
  variables.tf
Labels: enhancement

#24 Updated minio example module, updated README.md and small code fixes
  CHANGELOG.md
  Makefile
  README.md
  README_template.md
  dev/.env
  dev/ansible/01_generate_secrets_vault.yml
  dev/ansible/02_run_terraform.yml
  dev/ansible/03_run_tests.yml
  dev/ansible/04_upload_files.yml
  dev/vagrant/conf/post_bootstrap/00-install-plugin-vault-secrets-gen.yml
  example/main.tf
  example/nomad_acl.tf
  example/variables.tf
  template_example/.env
  template_example/dev/vagrant/conf/pre_bootstrap/00-prestart-example.yml
Labels: documentation, enhancement
